services:

  todoapp:
    build:
      context: .
      dockerfile: ./cmd/todoapp/Dockerfile
    container_name: todoapp
    depends_on:
      todoapp-postgres-migrate:
        condition: service_completed_successfully
    environment:
      - HTTP_ADDR=:5050
      - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT} 
      - POSTGRES_HOST=todoapp-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - TIME_ZONE=${TIME_ZONE}
      - LOGGER_FOLDER=/app/out/logs
    volumes:
      - ./out/logs:/app/out/logs
    ports:
      - "5050:5050"
    restart: always

  todoapp-postgres:
    image: postgres:17.9-bookworm
    container_name: todoapp-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data
    restart: always

  todoapp-postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@todoapp-postgres:5432/${POSTGRES_DB}?sslmode=disable" up

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: todoapp-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:todoapp-postgres:5432
    ports:
      - "5433:5432"
